import Image from "next/image"
import React from "react"
import { Carousel, Card } from "@/components/ui/apple-card-carousel"

export default function AppleCardsCarouselDemo() {
  const cards = data.map((card, index) => <Card key={card.src} card={card} index={index} />)

  return (
    <div className="w-full h-full py-20 bg-black">
      <h2 className="max-w-7xl pl-4 mx-auto text-xl md:text-5xl font-bold text-white font-sans">
       My others projects
      </h2>
      <Carousel items={cards} />
      <p className="text-right text-white pr-10 pt-6">* Some of these images are generated by AI</p>
    </div>
  )
}

const DummyContent = ({ href, category, txt }: { href: string, category: string, txt: string }) => {
    return (
      <div className="bg-neutral-900 p-8 md:p-14 rounded-3xl mb-4">
        <p className="text-neutral-400 text-base md:text-2xl font-sans max-w-3xl mx-auto">
          {category}: {txt}
        </p>
        <div className="flex justify-center">
          <a href={href} target="_blank" rel="noopener noreferrer">
            <button className="mt-10 px-4 py-2 bg-neutral-500 text-white rounded">Go to Link</button>
          </a>
        </div>
      </div>
    )
  }  
const data = [
    {
      category: "Portfolio",
      title: "This website 😄",
      src: "/img/portfolio.webp",
      href: "https://google.com",
      content: <DummyContent href="https://google.com" txt="This portfolio is an opportunity for me to showcase my work and explore the Next.js web technology."/>,
    },
    {
      category: "night of info 2024",
      title: "SWS-corp",
      src: "/img/night-info.webp",
      href: "https://github.com",
      content: <DummyContent href="https://github.com" category="night of info 2024" />,
    },
    {
      category: "School project - web",
      title: "TopTech : a website that lists the best tech devices",
      src: "/img/toptech.webp",
      href: "https://google.com",
      content: <DummyContent href="https://google.com" category="School project - web" />,
    },
    {
      category: "Web",
      title: "Oversim : help simracers with ai",
      src: "/img/oversim.webp",
      href: "https://google.com",
      content: <DummyContent href="https://google.com" category="Web" />,
    },
    {
      category: "C# Project",
      title: "All my C# apps",
      src: "/img/csharp.webp",
      href: "https://google.com",
      content: <DummyContent href="https://google.com" category="C# Project" />,
    },
    {
      category: "School project - Python",
      title: "All my python scripts",
      src: "https://images.unsplash.com/photo-1602081957921-9137a5d6eaee?q=80&w=2793&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      href: "https://google.com",
      content: <DummyContent href="https://google.com" category="School project - Python" />,
    },
  ]